import { randomUUID } from 'node:crypto';
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
const sum=(xs)=>xs.reduce((a,x)=>a+(Number(x.value ?? x.amount ?? 0)||0),0);
export function financeOverview(input={}){const assets=input.assets||[],liabilities=input.liabilities||[],income=input.income||[],expenses=input.expenses||[];const assetTotal=sum(assets),debtTotal=sum(liabilities),netWorth=assetTotal-debtTotal,monthlyIncome=sum(income),monthlyExpenses=sum(expenses),monthlyFreeCash=monthlyIncome-monthlyExpenses,liquid=sum(assets.filter(x=>['cash','checking','savings','money_market','liquid'].includes(String(x.type||'').toLowerCase()))),runwayMonths=monthlyExpenses>0?liquid/monthlyExpenses:null;return {schemaVersion:'FINANCE-1.0',assetTotal,debtTotal,netWorth,monthlyIncome,monthlyExpenses,monthlyFreeCash,savingsRate:monthlyIncome?clamp(monthlyFreeCash/monthlyIncome,-10,1):null,liquidAssets:liquid,runwayMonths,leverageRatio:assetTotal?debtTotal/assetTotal:null};}
export function budgetPlan(input={}){const income=Math.max(0,Number(input.monthlyIncome)||0),categories=input.categories||[],total=sum(categories),gap=income-total;return {schemaVersion:'BUDGET-1.0',monthlyIncome:income,planned:total,unallocated:gap,balanced:Math.abs(gap)<.01,targets:categories.map(c=>({name:c.name||'Unnamed',amount:Number(c.amount)||0,percent:income?((Number(c.amount)||0)/income)*100:null}))};}
export function debtPlan(input={}){const debts=(input.debts||[]).map(d=>({...d,balance:Math.max(0,Number(d.balance)||0),apr:Math.max(0,Number(d.apr)||0),minimum:Math.max(0,Number(d.minimum)||0)})),extra=Math.max(0,Number(input.extraMonthly)||0),ranked=[...debts].sort((a,b)=>(b.apr-a.apr)||(b.balance-a.balance)),balance=sum(debts.map(d=>d.balance)),weighted=debts.reduce((s,d)=>s+d.balance*d.apr,0);return {strategy:'AVALANCHE',totalDebt:balance,weightedApr:balance?weighted/balance:0,minimumMonthly:sum(debts.map(d=>d.minimum)),extraMonthly:extra,priority:ranked.map(d=>({id:d.id||d.name,apr:d.apr,balance:d.balance}))};}
export function cashflowForecast(input={}){const months=Math.max(1,Math.min(120,Number(input.months)||12));let balance=Number(input.startingCash)||0;const monthlyIn=Number(input.monthlyIncome)||0,monthlyOut=Number(input.monthlyExpenses)||0,growth=Number(input.incomeGrowthPct||0)/100,expenseGrowth=Number(input.expenseGrowthPct||0)/100,forecast=[];for(let i=1;i<=months;i++){const income=monthlyIn*Math.pow(1+growth,i-1),expenses=monthlyOut*Math.pow(1+expenseGrowth,i-1);balance+=income-expenses;forecast.push({month:i,income,expenses,netCashflow:income-expenses,balance});}return {schemaVersion:'CASHFLOW-1.0',forecast,lowestBalance:Math.min(...forecast.map(x=>x.balance)),endingBalance:balance};}
export function taxReserve(input={}){const income=Math.max(0,Number(input.annualIncome)||0),deductions=Math.max(0,Number(input.deductions)||0),effectiveRate=clamp((Number(input.effectiveRatePct)||0)/100,0,1),credits=Math.max(0,Number(input.credits)||0),taxable=Math.max(0,income-deductions),estimated=Math.max(0,taxable*effectiveRate-credits);return {schemaVersion:'TAX-1.0',disclaimer:'Planning estimate only; jurisdiction-specific filing requires a qualified tax professional.',annualIncome:income,deductions,taxableIncome:taxable,estimatedTax:estimated,reserveMonthly:estimated/12};}
export function goalPlan(input={}){const target=Math.max(0,Number(input.target)||0),current=Math.max(0,Number(input.current)||0),months=Math.max(1,Number(input.months)||1),annualReturn=Math.max(-.99,Number(input.annualReturnPct||0)/100),r=Math.pow(1+annualReturn,1/12)-1,n=months,futureCurrent=current*Math.pow(1+r,n);const payment=r?Math.max(0,(target-futureCurrent)*r/(Math.pow(1+r,n)-1)):Math.max(0,(target-current)/n);return {schemaVersion:'GOAL-1.0',target,current,months,assumedAnnualReturnPct:annualReturn*100,requiredMonthlyContribution:Math.max(0,payment),gapNow:Math.max(0,target-current)};}
export function financialHealth(input={}){const o=financeOverview(input),emergency=o.runwayMonths==null?0:Math.min(6,o.runwayMonths)/6,debt=o.leverageRatio==null?1:Math.max(0,1-Math.min(1,o.leverageRatio)),savings=o.savingsRate==null?0:clamp(o.savingsRate,0,1),score=Math.round(100*(.4*emergency+.3*debt+.3*savings)),tier=score>=80?'STRONG':score>=60?'HEALTHY':score>=40?'WATCH':'FRAGILE';return {schemaVersion:'HEALTH-1.0',score,tier,drivers:{emergencyFund:o.runwayMonths,debtLoad:o.leverageRatio,savingsRate:o.savingsRate},id:randomUUID()};}
